A1=1;
A2=2;
A3=1;
f1=10;
f2=20;
f3=30;
fs=200;t=0:1/fs:1;
x=A1*cos(2*pi*f1*t + pi/3)+ A2*cos(2*pi*f2*t+pi/4)- A3*cos(2*pi*f3*t+pi/6);
X1=fft(x);
X2=abs(X1);
X3=fftshift(X2);
z=angle(X1);
n=length(X2);
c=0:fs/n:fs-fs/n;
c1=-fs/2:fs/n: fs/2 - fs/n;
subplot(2,4,1),plot(t,x);
xlabel('time');ylabel('amplitude');title('Time Domain Representation of 3 Tone Signal');
subplot(2,4,2),plot(c,X1);
xlabel('frequency');ylabel('Magnitude');title('One sided response');
subplot(2,4,3),plot(c,X2);
xlabel('frequency');ylabel('Magnitude');title('One sided Magnitude response');
subplot(2,4,4),plot(c,X3);
xlabel('frequency');ylabel('Magnitude');title('One sided response Centre');
subplot(2,4,5),plot(c1,X1);
xlabel('frequency');ylabel('Magnitude');title('Two sided response');
subplot(2,4,6),plot(c1,X2);
xlabel('frequency');ylabel('Magnitude');title('Two sided Magnitude response');
subplot(2,4,7),plot(c1,X3);
xlabel('frequency');ylabel('Magnitude');title('Two sided Magnitude response centre ');
subplot(2,4,8)
plot(c1,z,'-r',c,z,'-g');
legend('Two sided','one sided');
xlabel('frequency');ylabel('Magnitude');title('Two sided Phase response');